const DataExtraction = () => {
  const temp = {
    solana: {
      assetName: "solana",
      assetId: "SOL",
      assetLink: "https://solana.com",
      officalLaunchDate: "March 2020",
      updates: [
        "The release of v1.16. This release included a number of performance improvements, as well as the introduction of new features such as merkle shreds and priority queues.",
        "The rollout of QUIC TPU. QUIC TPU is a new networking protocol that improves the throughput and latency of Solana's network.",
        "The introduction of stake-weighted QoS. Stake-weighted QoS is a new feature that prioritizes transactions from validators with more stake. This helps to ensure that high-value transactions are processed more quickly.",
      ],
      assetDesc:
        "Solana is a high-performance blockchain platform that can process up to 50,000 transactions per second. It is designed to be scalable, secure, and energy-efficient. Solana uses a proof-of-history (PoH) consensus mechanism, which is a combination of proof-of-stake (PoS) and timekeeping. PoH allows Solana to achieve high throughput and low latency without sacrificing security.",
      price: {
        value: "$28.41",
        change: "up",
        changeValue: "14%",
      },
      marketCapitalization: {
        value: "$10.68B",
        change: "up",
        changeValue: "14%",
      },
      numProjectsLaunched: {
        value: "354",
        change: "up",
        changeValue: "11%",
      },
      numDevelopers: {
        value: "2000+",
        change: "down",
        changeValue: "1%",
      },
      numOutstandingCoins: {
        value: "402.68M",
        change: "up",
        changeValue: "1%",
      },
      numTransactions: {
        value: "175.34B",
        change: "up",
        changeValue: "24%",
      },
      totalValueLocked: {
        value: "$1.09B",
        change: "up",
        changeValue: "13%",
      },
      numActiveProposals: {
        value: "11",
        change: "up",
        changeValue: "4%",
      },
      overallRisk: "72%",
      regulatoryRisk: {
        value: "68%",
        text: "Solana is still in its early stages of development, and there is a risk that governments could introduce regulations that could adversely affect the price.",
      },
      volatility: {
        value: "72%",
        text: "The price of Solana is volatile, and it could experience significant price swings in the future.",
      },
      lackOfAdoption: {
        value: "76%",
        text: "Solana is still a relatively isNewMember platform, and it is not yet as widely adopted as other blockchain platforms. This could limit the demand for Solana and its price potential.",
      },
      perspectives: {
        profilePic: "",
        text: "If 2021 was the year that the Solana community stepped into the sunlight, 2022 was the year for shipping and scaling. And what a year it’s been! There’s been the highs of Breakpoint and the lows of the volatile market. Throughout it all, the Solana community has only gotten stronger — and kept their heads down to keep on building. As we once again arrive at the Solana Happening, it’s important to take a breath, take stock of what we’ve done and get excited for what’s to come.",
        name: " Anatoly Yakovenko",
        role: "CEO & Co-Founder, Solana Labs",
      },
      announcements: [
        {
          timeStamp: "Jul 2023",
          title: "Solana Pay",
          text: "Solana Pay, introduced in February, has kickstarted a frictionless, permissionless payment ecosystem. It’s now being used by stores and brands alike — and will continue to grow in 2023.",
          announcementLink: "https://www.google.com/",
        },
        {
          timeStamp: "Feb 2023",
          title: "Stripe",
          text: "In December Stripe debued its fiat to crypto payments onramp with 11 of 16 projects in the program built upon Solana",
          announcementLink: "https://www.google.com/",
        },
        {
          timeStamp: "Nov 2022",
          title: "DeFi Community",
          text: "The developer community is taking notice and we have seen a significant increase in the number of developers building upon Solana. For example in November 2022, 2053 active developers were working on projects of which 1654 were Solana exclusive. This represents an increase over the same period last year of 115%",
          announcementLink: "https://www.google.com/",
        },
        {
          timeStamp: "Nov 2022",
          title: "Google Cloud",
          text: "On November 5th, Google Cloud announced that they have been running a block-chain supporting Solana Validator while extending support for Blockchain Node Engine to Solana enabling anyone in the world to run a validator in the cloud.",
          announcementLink: "https://www.google.com/",
        },
        {
          timeStamp: "Aug 2022",
          title: "Brave",
          text: "Last August Brave browser announced that they have integrated Solana into their wallet providing native support for Solana dApps in their mobile and web browsers",
          announcementLink: "https://www.google.com/",
        },
        {
          timeStamp: "Jul 2022",
          title: "Solana Space",
          text: "Solana Spaces, a company dedicated to bringing the Solana community off the internet and into retail spaces, has opened two locations in the last year. The two locations, one in isNewMember York City and their flagship Solana Embassy in Miami, showcase projects from the ecosystem and help onboard isNewMember users. And with SpacesDAO, their isNewMember decentralized approach to franchising, Solana Spaces will be coming to locations literally around the world.",
          announcementLink: "https://www.google.com/",
        },
      ],
      volume24H: "$259,643,154",
      typicalHoldTime: "86 days",
      revenue30D: "$512,860",
      fullyDilutedValuation: "$9,154,137,050",
      circulatingSupply: "399,923,253",
      totalSupply: "551,008,309",
      maxSupply: "--",
      trailing12Months: "NA",
      feeRevenue: "",
      tokenomicsDesc:
        "Tokenomics is the science that explores the elements that make a crypto asset valuable. It studies the relationship between an asset’s supply, inflation rate, distribution, utility and accessibility to analyze and predict its success.",
      tokenomicsOverallScore: 84,
      supply: 74,
      inflationRate: 74,
      distribution: 74,
      utility: 94,
      accessibility: 91,
      tokenLiquidSupply: 348,
      tokenTotalSupply: 511,
      tokenOutstandingSupply: 163,
      supplySchedule: "",
      supplyScheduleDesc:
        "A plan that outlines how many tokens will be released into circulation over time.",
      tokenAllocationDesc:
        "The way in which tokens are distributed between the different stakeholder groups of a crypto project.",
      totalTokenAllocations: "",
      tokenAllocationOverTime: "",
      incentivesDesc:
        "The mechanisms that are used to encourage people to participate in the network and to ensure that the network is secure and reliable.",
      incentivesMiners: [
        "Miners are rewarded every time they create a isNewMember block in the chain",
        "They are rewarded with a small commission for each transaction included in the chain.",
      ],
      incentivesInverstors: [
        "Crypto staking rewards are the digital equivalent of interest or dividends, and they can allow owners to earn passive income while holding onto their underlying assets.",
      ],
      networkPlatformActivityDesc:
        "The amount of activity that is happening on a particular blockchain network or platform.",
      totalTransactions: {
        value: "200.23B",
        change: "up",
        changeValue: "14%",
      },
      dailyTransactions: {
        value: "4.55M",
        change: "up",
        changeValue: "14%",
      },
      uniqueWalletAddresses: {
        value: "9.52M",
        change: "up",
        changeValue: "11%",
      },
      nftVolume: {
        value: "$1.21B",
        change: "up",
        changeValue: "9%",
      },
      totalMarketplaces: {
        value: "20",
        change: "up",
        changeValue: "14%",
      },
      totalDevelopers: {
        value: "24.22",
        change: "up",
        changeValue: "10%",
      },
      numTotalApps: {
        value: "423",
        change: "up",
        changeValue: "34%",
      },
      tradingApps: {
        value: "26",
        change: "up",
        changeValue: "65%",
      },
      lendingBorrowingApps: {
        value: "18",
        change: "up",
        changeValue: "34%",
      },
      appsEarningInterest: {
        value: "174",
        change: "up",
        changeValue: "56%",
      },
      paymentApps: {
        value: "26",
        change: "up",
        changeValue: "17%",
      },
      numTotalNFTs: {
        value: "32.32M",
        change: "up",
        changeValue: "21%",
      },
      web3GamingApps: {
        value: "353",
        change: "up",
        changeValue: "5%",
      },
      socialMediaApps: {
        value: "17",
        change: "up",
        changeValue: "14%",
      },
      enterpriseApps: {
        value: "83",
        change: "up",
        changeValue: "15%",
      },
      networkActivityLink: "https://solana.com/ecosystem/explore",
      founders: [
        {
          profilePic: "",
          name: "Anatoly Yakovenko",
          role: "CEO & Co-Founder",
          desc: "Yakovenko is a software engineer with over 20 years of experience in the tech industry. He previously worked at Qualcomm, Dropbox, and Mesosphere.",
          linkedInUrl: "https://www.linkedin.com",
          numTokenHeld: "XX,XXX,XXX",
          percentTokenHeld: "XX.XX%",
          change30D: "+X.XX%",
          ttmChange: "+XX.XX%",
        },
        {
          profilePic: "",
          name: "Raj Gokal",
          role: "COO & Co-Founder",
          desc: "Gokal is a software engineer with over 10 years of experience in the tech industry. He previously worked at Dropbox and Google.",
          linkedInUrl: "https://www.linkedin.com",
          numTokenHeld: "XX,XXX,XXX",
          percentTokenHeld: "XX.XX%",
          change30D: "+X.XX%",
          ttmChange: "+XX.XX%",
        },
        {
          profilePic: "",
          name: "Stephen Akridge",
          role: "Co-Founder",
          desc: "Akridge is a software engineer with over 15 years of experience in the tech industry. He previously worked at Qualcomm and Mesosphere.",
          linkedInUrl: "https://www.linkedin.com",
          numTokenHeld: "XX,XXX,XXX",
          percentTokenHeld: "XX.XX%",
          change30D: "+X.XX%",
          ttmChange: "+XX.XX%",
        },
        {
          profilePic: "",
          name: "Greg Fitzgerald",
          role: "CTO & Co-Founder",
          desc: "Fitzgerald is a software engineer with over 10 years of experience in the tech industry. He previously worked at Qualcomm and Dropbox.",
          linkedInUrl: "https://www.linkedin.com",
          numTokenHeld: "XX,XXX,XXX",
          percentTokenHeld: "XX.XX%",
          change30D: "+X.XX%",
          ttmChange: "+XX.XX%",
        },
      ],
      management: [
        {
          profilePic: "",
          name: "Lily Liu",
          role: "Executive Director of Ecosystem",
          desc: "Liu is responsible for leading the Solana Foundation's efforts to grow and support the Solana ecosystem. She has over 10 years of experience in the tech industry.",
          linkedInUrl: "https://www.linkedin.com",
          isNewMember: false,
          numTokenHeld: "XX,XXX",
          percentTokenHeld: "XX.XX%",
          change30D: "+X.XX%",
          ttmChange: "+XX.XX%",
        },
        {
          profilePic: "",
          name: "Daniel Albert",
          role: "Executive Director of Grants",
          desc: "Albert is responsible for overseeing the Solana Foundation's grant program, which provides funding to projects that are building on the Solana blockchain.",
          linkedInUrl: "https://www.linkedin.com",
          isNewMember: false,
          numTokenHeld: "XX,XXX",
          percentTokenHeld: "XX.XX%",
          change30D: "+X.XX%",
          ttmChange: "+XX.XX%",
        },
        {
          profilePic: "",
          name: "Matthew Wyndowe",
          role: "Executive Director of Operations",
          desc: "Wyndowe is responsible for overseeing the Solana Foundation's day-to-day operations. He has over 10 years of experience in the tech industry.",
          linkedInUrl: "https://www.linkedin.com",
          isNewMember: true,
          numTokenHeld: "XX,XXX",
          percentTokenHeld: "XX.XX%",
          change30D: "+X.XX%",
          ttmChange: "+XX.XX%",
        },
      ],
      investors: [
        {
          name: "investor Name",
          numTokenHeld: "XX,XXX",
          percentTokenHeld: "XX.XX%",
          change30D: "+X.XX%",
          ttmChange: "+XX.XX%",
        },
        {
          name: "investor Name",
          numTokenHeld: "XX,XXX",
          percentTokenHeld: "XX.XX%",
          change30D: "+X.XX%",
          ttmChange: "+XX.XX%",
        },
        {
          name: "investor Name",
          numTokenHeld: "XX,XXX",
          percentTokenHeld: "XX.XX%",
          change30D: "+X.XX%",
          ttmChange: "+XX.XX%",
        },
        {
          name: "investor Name",
          numTokenHeld: "XX,XXX",
          percentTokenHeld: "XX.XX%",
          change30D: "+X.XX%",
          ttmChange: "+XX.XX%",
        },
      ],
      governanceDesc:
        "Governance tokens are a type of cryptocurrency that allow tokenholders to vote on the direction of a blockchain project. The primary purpose of governance tokens is to decentralize decision-making and to give holders a say in how the project is run.",
      methodologyDesc:
        "Solana's governance methodology provides core building blocks and primitives to create Decentralized Autonomous Organizations (DAOs) on the Solana blockchain. The program is DAO type and asset type agnostic and can be used to build any type of DAOs which can own and manage any type of assets. Overall, Solana's governance methodology is designed to be efficient, secure, and accessible to all users.",
      methodologyLink: "https://solana.com",
      numTotalProposals: "294",
      numHolders: "452M",
      numVoters: "332M",
      voterTurnout: "48%",
      numVotes: "800M+",
      votingDuration: "14 Days",
      voteOutcomeDistribution: {
        yes: "85%",
        no: "9%",
        abstain: "5%",
      },
      vetoPowerUtilization: "2%",
      approvalRate: "84%",
      numIdeasSubmitted: "239",
      numAcceptedProposals: "2K+",
      numImplementedProposals: "1K+",
      proposalCategories: [
        {
          categoryName: "Protocol Changes",
          numTotalProposals: 59,
          voteOutcomeYes: 40,
          voteOutcomeNo: 10,
          voteOutcomeAbstain: 9,
          numAccepted: 40,
          numImplemented: 27,
          numActive: 2,
          subCategories: [
            {
              categoryName: "Underlying Protocol",
              numTotalProposals: 38,
              voteOutcomeYes: 30,
              voteOutcomeNo: 2,
              voteOutcomeAbstain: 6,
              numAccepted: 30,
              numImplemented: 16,
              numActive: 1,
            },
            {
              categoryName: "Consensus Mechanism",
              numTotalProposals: 10,
              voteOutcomeYes: 10,
              voteOutcomeNo: 0,
              voteOutcomeAbstain: 0,
              numAccepted: 10,
              numImplemented: 5,
              numActive: 1,
            },
            {
              categoryName: "Block Size",
              numTotalProposals: 5,
              voteOutcomeYes: 3,
              voteOutcomeNo: 1,
              voteOutcomeAbstain: 1,
              numAccepted: 5,
              numImplemented: 3,
              numActive: 0,
            },
            {
              categoryName: "Transaction Speed",
              numTotalProposals: 3,
              voteOutcomeYes: 2,
              voteOutcomeNo: 1,
              voteOutcomeAbstain: 1,
              numAccepted: 3,
              numImplemented: 2,
              numActive: 0,
            },
            {
              categoryName: "Other Technical Aspects",
              numTotalProposals: 3,
              voteOutcomeYes: 1,
              voteOutcomeNo: 1,
              voteOutcomeAbstain: 1,
              numAccepted: 3,
              numImplemented: 1,
              numActive: 0,
            },
          ],
        },
        {
          categoryName: "Governance Structure",
          numTotalProposals: 43,
          voteOutcomeYes: 35,
          voteOutcomeNo: 5,
          voteOutcomeAbstain: 3,
          numAccepted: 35,
          numImplemented: 18,
          numActive: 2,
          subCategories: [
            {
              categoryName: "Underlying Protocol",
              numTotalProposals: 38,
              voteOutcomeYes: 30,
              voteOutcomeNo: 2,
              voteOutcomeAbstain: 6,
              numAccepted: 30,
              numImplemented: 16,
              numActive: 1,
            },
            {
              categoryName: "Consensus Mechanism",
              numTotalProposals: 10,
              voteOutcomeYes: 10,
              voteOutcomeNo: 0,
              voteOutcomeAbstain: 0,
              numAccepted: 10,
              numImplemented: 5,
              numActive: 1,
            },
            {
              categoryName: "Block Size",
              numTotalProposals: 5,
              voteOutcomeYes: 3,
              voteOutcomeNo: 1,
              voteOutcomeAbstain: 1,
              numAccepted: 5,
              numImplemented: 3,
              numActive: 0,
            },
            {
              categoryName: "Transaction Speed",
              numTotalProposals: 3,
              voteOutcomeYes: 2,
              voteOutcomeNo: 1,
              voteOutcomeAbstain: 1,
              numAccepted: 3,
              numImplemented: 2,
              numActive: 0,
            },
            {
              categoryName: "Other Technical Aspects",
              numTotalProposals: 3,
              voteOutcomeYes: 1,
              voteOutcomeNo: 1,
              voteOutcomeAbstain: 1,
              numAccepted: 3,
              numImplemented: 1,
              numActive: 0,
            },
          ],
        },
        {
          categoryName: "Tokenomics",
          numTotalProposals: 40,
          voteOutcomeYes: 38,
          voteOutcomeNo: 2,
          voteOutcomeAbstain: 0,
          numAccepted: 38,
          numImplemented: 25,
          numActive: 2,
          subCategories: [
            {
              categoryName: "Underlying Protocol",
              numTotalProposals: 38,
              voteOutcomeYes: 30,
              voteOutcomeNo: 2,
              voteOutcomeAbstain: 6,
              numAccepted: 30,
              numImplemented: 16,
              numActive: 1,
            },
            {
              categoryName: "Consensus Mechanism",
              numTotalProposals: 10,
              voteOutcomeYes: 10,
              voteOutcomeNo: 0,
              voteOutcomeAbstain: 0,
              numAccepted: 10,
              numImplemented: 5,
              numActive: 1,
            },
            {
              categoryName: "Block Size",
              numTotalProposals: 5,
              voteOutcomeYes: 3,
              voteOutcomeNo: 1,
              voteOutcomeAbstain: 1,
              numAccepted: 5,
              numImplemented: 3,
              numActive: 0,
            },
            {
              categoryName: "Transaction Speed",
              numTotalProposals: 3,
              voteOutcomeYes: 2,
              voteOutcomeNo: 1,
              voteOutcomeAbstain: 1,
              numAccepted: 3,
              numImplemented: 2,
              numActive: 0,
            },
            {
              categoryName: "Other Technical Aspects",
              numTotalProposals: 3,
              voteOutcomeYes: 1,
              voteOutcomeNo: 1,
              voteOutcomeAbstain: 1,
              numAccepted: 3,
              numImplemented: 1,
              numActive: 0,
            },
          ],
        },
        {
          categoryName: "Security Enhancements",
          numTotalProposals: 34,
          voteOutcomeYes: 30,
          voteOutcomeNo: 2,
          voteOutcomeAbstain: 2,
          numAccepted: 30,
          numImplemented: 22,
          numActive: 1,
          subCategories: [
            {
              categoryName: "Underlying Protocol",
              numTotalProposals: 38,
              voteOutcomeYes: 30,
              voteOutcomeNo: 2,
              voteOutcomeAbstain: 6,
              numAccepted: 30,
              numImplemented: 16,
              numActive: 1,
            },
            {
              categoryName: "Consensus Mechanism",
              numTotalProposals: 10,
              voteOutcomeYes: 10,
              voteOutcomeNo: 0,
              voteOutcomeAbstain: 0,
              numAccepted: 10,
              numImplemented: 5,
              numActive: 1,
            },
            {
              categoryName: "Block Size",
              numTotalProposals: 5,
              voteOutcomeYes: 3,
              voteOutcomeNo: 1,
              voteOutcomeAbstain: 1,
              numAccepted: 5,
              numImplemented: 3,
              numActive: 0,
            },
            {
              categoryName: "Transaction Speed",
              numTotalProposals: 3,
              voteOutcomeYes: 2,
              voteOutcomeNo: 1,
              voteOutcomeAbstain: 1,
              numAccepted: 3,
              numImplemented: 2,
              numActive: 0,
            },
            {
              categoryName: "Other Technical Aspects",
              numTotalProposals: 3,
              voteOutcomeYes: 1,
              voteOutcomeNo: 1,
              voteOutcomeAbstain: 1,
              numAccepted: 3,
              numImplemented: 1,
              numActive: 0,
            },
          ],
        },
        {
          categoryName: "FundingBudget Allocation",
          numTotalProposals: 33,
          voteOutcomeYes: 22,
          voteOutcomeNo: 8,
          voteOutcomeAbstain: 3,
          numAccepted: 22,
          numImplemented: 15,
          numActive: 1,
          subCategories: [
            {
              categoryName: "Underlying Protocol",
              numTotalProposals: 38,
              voteOutcomeYes: 30,
              voteOutcomeNo: 2,
              voteOutcomeAbstain: 6,
              numAccepted: 30,
              numImplemented: 16,
              numActive: 1,
            },
            {
              categoryName: "Consensus Mechanism",
              numTotalProposals: 10,
              voteOutcomeYes: 10,
              voteOutcomeNo: 0,
              voteOutcomeAbstain: 0,
              numAccepted: 10,
              numImplemented: 5,
              numActive: 1,
            },
            {
              categoryName: "Block Size",
              numTotalProposals: 5,
              voteOutcomeYes: 3,
              voteOutcomeNo: 1,
              voteOutcomeAbstain: 1,
              numAccepted: 5,
              numImplemented: 3,
              numActive: 0,
            },
            {
              categoryName: "Transaction Speed",
              numTotalProposals: 3,
              voteOutcomeYes: 2,
              voteOutcomeNo: 1,
              voteOutcomeAbstain: 1,
              numAccepted: 3,
              numImplemented: 2,
              numActive: 0,
            },
            {
              categoryName: "Other Technical Aspects",
              numTotalProposals: 3,
              voteOutcomeYes: 1,
              voteOutcomeNo: 1,
              voteOutcomeAbstain: 1,
              numAccepted: 3,
              numImplemented: 1,
              numActive: 0,
            },
          ],
        },
        {
          categoryName: "Community Initiatives",
          numTotalProposals: 30,
          voteOutcomeYes: 30,
          voteOutcomeNo: 0,
          voteOutcomeAbstain: 0,
          numAccepted: 30,
          numImplemented: 26,
          numActive: 1,
          subCategories: [
            {
              categoryName: "Underlying Protocol",
              numTotalProposals: 38,
              voteOutcomeYes: 30,
              voteOutcomeNo: 2,
              voteOutcomeAbstain: 6,
              numAccepted: 30,
              numImplemented: 16,
              numActive: 1,
            },
            {
              categoryName: "Consensus Mechanism",
              numTotalProposals: 10,
              voteOutcomeYes: 10,
              voteOutcomeNo: 0,
              voteOutcomeAbstain: 0,
              numAccepted: 10,
              numImplemented: 5,
              numActive: 1,
            },
            {
              categoryName: "Block Size",
              numTotalProposals: 5,
              voteOutcomeYes: 3,
              voteOutcomeNo: 1,
              voteOutcomeAbstain: 1,
              numAccepted: 5,
              numImplemented: 3,
              numActive: 0,
            },
            {
              categoryName: "Transaction Speed",
              numTotalProposals: 3,
              voteOutcomeYes: 2,
              voteOutcomeNo: 1,
              voteOutcomeAbstain: 1,
              numAccepted: 3,
              numImplemented: 2,
              numActive: 0,
            },
            {
              categoryName: "Other Technical Aspects",
              numTotalProposals: 3,
              voteOutcomeYes: 1,
              voteOutcomeNo: 1,
              voteOutcomeAbstain: 1,
              numAccepted: 3,
              numImplemented: 1,
              numActive: 0,
            },
          ],
        },
        {
          categoryName: "Partnerships Integrations",
          numTotalProposals: 28,
          voteOutcomeYes: 23,
          voteOutcomeNo: 4,
          voteOutcomeAbstain: 1,
          numAccepted: 23,
          numImplemented: 17,
          numActive: 1,
          subCategories: [
            {
              categoryName: "Underlying Protocol",
              numTotalProposals: 38,
              voteOutcomeYes: 30,
              voteOutcomeNo: 2,
              voteOutcomeAbstain: 6,
              numAccepted: 30,
              numImplemented: 16,
              numActive: 1,
            },
            {
              categoryName: "Consensus Mechanism",
              numTotalProposals: 10,
              voteOutcomeYes: 10,
              voteOutcomeNo: 0,
              voteOutcomeAbstain: 0,
              numAccepted: 10,
              numImplemented: 5,
              numActive: 1,
            },
            {
              categoryName: "Block Size",
              numTotalProposals: 5,
              voteOutcomeYes: 3,
              voteOutcomeNo: 1,
              voteOutcomeAbstain: 1,
              numAccepted: 5,
              numImplemented: 3,
              numActive: 0,
            },
            {
              categoryName: "Transaction Speed",
              numTotalProposals: 3,
              voteOutcomeYes: 2,
              voteOutcomeNo: 1,
              voteOutcomeAbstain: 1,
              numAccepted: 3,
              numImplemented: 2,
              numActive: 0,
            },
            {
              categoryName: "Other Technical Aspects",
              numTotalProposals: 3,
              voteOutcomeYes: 1,
              voteOutcomeNo: 1,
              voteOutcomeAbstain: 1,
              numAccepted: 3,
              numImplemented: 1,
              numActive: 0,
            },
          ],
        },
        {
          categoryName: "Environmental Impact",
          numTotalProposals: 27,
          voteOutcomeYes: 24,
          voteOutcomeNo: 2,
          voteOutcomeAbstain: 1,
          numAccepted: 24,
          numImplemented: 17,
          numActive: 1,
          subCategories: [
            {
              categoryName: "Underlying Protocol",
              numTotalProposals: 38,
              voteOutcomeYes: 30,
              voteOutcomeNo: 2,
              voteOutcomeAbstain: 6,
              numAccepted: 30,
              numImplemented: 16,
              numActive: 1,
            },
            {
              categoryName: "Consensus Mechanism",
              numTotalProposals: 10,
              voteOutcomeYes: 10,
              voteOutcomeNo: 0,
              voteOutcomeAbstain: 0,
              numAccepted: 10,
              numImplemented: 5,
              numActive: 1,
            },
            {
              categoryName: "Block Size",
              numTotalProposals: 5,
              voteOutcomeYes: 3,
              voteOutcomeNo: 1,
              voteOutcomeAbstain: 1,
              numAccepted: 5,
              numImplemented: 3,
              numActive: 0,
            },
            {
              categoryName: "Transaction Speed",
              numTotalProposals: 3,
              voteOutcomeYes: 2,
              voteOutcomeNo: 1,
              voteOutcomeAbstain: 1,
              numAccepted: 3,
              numImplemented: 2,
              numActive: 0,
            },
            {
              categoryName: "Other Technical Aspects",
              numTotalProposals: 3,
              voteOutcomeYes: 1,
              voteOutcomeNo: 1,
              voteOutcomeAbstain: 1,
              numAccepted: 3,
              numImplemented: 1,
              numActive: 0,
            },
          ],
        },
      ],
      whitePaper: "https://solana.com/solana-whitepaper.pdf",
      sourceCodeRepo: "https://github.com/solana-labs",
      blockExplorer: "https://explorer.solana.com",
    },
    bitcoin: {
      assetName: "Bitcoin",
      assetId: "BTC",
      updates: [
        "The Lightning Network has seen massive growth. The Lightning Network is a layer-2 scaling solution for Bitcoin that allows for instant, cheap payments off-chain. In 2022, the network's publicly visible liquidity capacity rose from 1,058 BTC to more than 4,771 BTC, the number of Lightning Network channels rose by +80%, from 37,298 to 67,339 channels, and the number of publicly visible Lightning Network nodes increased by +88%, from 8,295 to 15,636 nodes.",
        "Bitcoin adoption is growing. There are now more businesses accepting Bitcoin than ever before, and the number of people holding Bitcoin is also increasing. In 2022, El Salvador became the first country to adopt Bitcoin as legal tender, and several other countries are considering doing the same.",
        "Bitcoin is becoming more regulated. Governments around the world are starting to regulate Bitcoin and other cryptocurrencies. This is partly due to concerns about money laundering and terrorist financing, but it is also due to the growing popularity of Bitcoin.",
      ],
      price: {
        value: "$29.58K",
        change: "down",
        changeValue: "5.48%",
      },
      marketCapitalization: {
        value: "$576.34B",
        change: "down",
        changeValue: "22.65%",
      },
      numOutstandingCoins: {
        value: "21.00M",
        change: "NA",
      },
    },
    ethereum: {
      assetName: "Ethereum",
      assetId: "ETH",
      updates: [
        "The Merge: This upgrade is scheduled to be deployed in 2023, and it will transition Ethereum from a proof-of-work consensus mechanism to a proof-of-stake consensus mechanism. This will make Ethereum more scalable, secure, and energy-efficient.",
        "Sharding: This upgrade is scheduled to be deployed after The Merge, and it will divide the Ethereum blockchain into smaller pieces, called shards. This will further improve Ethereum's scalability.",
        "EIP-1559: This upgrade was deployed on August 5, 2021, and it changed the way that transaction fees are calculated on Ethereum. This has made Ethereum's transaction fees more predictable and stable.",
      ],
      price: {
        value: "$1,841.72",
        change: "down",
        changeValue: "4.70%",
      },
      marketCapitalization: {
        value: "$221.27B",
        change: "down",
        changeValue: "0.08%",
      },
      numOutstandingCoins: {
        value: "120.14M",
        change: "NA",
      },
    },
    dogecoin: {
      assetName: "Dogecoin",
      assetId: "DOGE",
      updates: [
        "Dogecoin Foundation: In February 2023, a new Dogecoin Foundation was formed to help guide the future of the coin. The foundation is led by Billy Markus, the co-creator of Dogecoin, and Elon Musk, the CEO of Tesla and SpaceX.",
        "Tesla acceptance: In March 2023, Tesla announced that it would start accepting Dogecoin as payment for some merchandise. This was a major step forward for Dogecoin, as it gave the coin more real-world utility.",
        "Twitter integration: In April 2023, Elon Musk announced that he would be integrating Dogecoin into Twitter. This would allow users to tip each other with Dogecoin and pay for Twitter Blue subscriptions with Dogecoin.",
      ],
      price: {
        value: "$0.075",
        change: "down",
        changeValue: "2.33%",
      },
      marketCapitalization: {
        value: "$10.50B",
        change: "down",
        changeValue: "0.08%",
      },
      numOutstandingCoins: {
        value: "140.59B",
        change: "up",
        changeValue: "1.69%",
      },
    },
    usdCoin: {
      assetName: "USD COIN",
      assetId: "USDC",
      updates: [
        "Circle takes equity stake in Coinbase: In March 2023, Circle announced that it had taken an equity stake in Coinbase. This was a major step forward for USDC, as it gave the stablecoin a strong backing from one of the most well-known cryptocurrency exchanges.",
        "USDC pools available to all investors: In April 2023, Circle announced that it was making USDC pools available to all investors. This was a major step forward for USDC, as it made it easier for investors to earn interest on their USDC holdings.",
        "USDC on Solana: In June 2023, USDC was launched on the Solana blockchain. This was a major step forward for USDC, as it made it available on a new blockchain with high scalability and low transaction fees.",
      ],
      price: {
        value: "$1",
        change: "nochange",
        changeValue: "0.00%",
      },
      marketCapitalization: {
        value: "$26.03B",
        change: "up",
        changeValue: "2.16%",
      },
      numOutstandingCoins: {
        value: "$26.03B",
        change: "up",
        changeValue: "??%",
      },
    },
    xrp: {
      assetName: "XRP",
      assetId: "XRP",
      updates: [],
      price: {
        value: "$0.63",
        change: "down",
        changeValue: "29.44%",
      },
      marketCapitalization: {
        value: "$33.32B",
        change: "down",
        changeValue: "38.21%",
      },
      numOutstandingCoins: {
        value: "$100.00B",
        change: "nochange",
        changeValue: "0.00%",
      },
    },
  };
  const temp1 = [
    {
      src: "/_next/static/media/brand=Solana.21cab6dc.png",
      height: 44,
      width: 44,
      blurDataURL:
        "/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fbrand%3DSolana.21cab6dc.png&w=8&q=70",
      blurWidth: 8,
      blurHeight: 8,
    },
    {
      src: "/_next/static/media/icon-bitcoin.3baaf262.png",
      height: 24,
      width: 24,
      blurDataURL:
        "/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Ficon-bitcoin.3baaf262.png&w=8&q=70",
      blurWidth: 8,
      blurHeight: 8,
    },
    {
      src: "/_next/static/media/icon-ethereum.dd5b738c.png",
      height: 24,
      width: 24,
      blurDataURL:
        "/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Ficon-ethereum.dd5b738c.png&w=8&q=70",
      blurWidth: 8,
      blurHeight: 8,
    },
    {
      src: "/_next/static/media/icon-dogecoin.3a429f33.png",
      height: 24,
      width: 24,
      blurDataURL:
        "/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Ficon-dogecoin.3a429f33.png&w=8&q=70",
      blurWidth: 8,
      blurHeight: 8,
    },
    {
      src: "/_next/static/media/icon-usdcoin.fe8d838d.png",
      height: 24,
      width: 24,
      blurDataURL:
        "/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Ficon-usdcoin.fe8d838d.png&w=8&q=70",
      blurWidth: 8,
      blurHeight: 8,
    },
    {
      src: "/_next/static/media/icon-xrp.2abb88ae.png",
      height: 24,
      width: 24,
      blurDataURL:
        "/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Ficon-xrp.2abb88ae.png&w=8&q=70",
      blurWidth: 8,
      blurHeight: 8,
    },
  ];
  const result = [];
  for (var key in temp) {
    if (temp.hasOwnProperty(key)) {
      result.push({
        assetName: temp[key].assetName,
        assetId: temp[key].assetId,
        updates: temp[key].updates,
        price: {
          value: temp[key].price["value"],
          change: temp[key].price["change"],
        },
        marketCapitalization: temp[key].marketCapitalization.value,
        numOutstandingCoins: temp[key].numOutstandingCoins.value,
      });
    }
  }
  // console.log(temp1.map((d) => d.src));
  // console.log(result);
};

export default DataExtraction;
